---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - name: Create resource group
      azure_rm_resourcegroup:
        name: rg-cs-ansible
        location: eastus

    - name: Create Ansible Key Vault
      azure_rm_keyvault:
        resource_group: rg-cs-ansible
        vault_name: kv-cs-ansible
        vault_tenant: <tenant_id>
        enabled_for_deployment: yes
        sku:
          name: standard
        access_policies:
          - tenant_id: <tenant_id>
            object_id: <object_id>
            secrets:
              - get
              - list
              - set

    - name: Get Key Vault by name
      azure_rm_keyvault_info:
        resource_group: rg-cs-ansible
        name: kv-cs-ansible
      register: keyvault

    - name: set KeyVault uri fact
      set_fact: keyvaulturi="{{ keyvault | json_query('keyvaults[0].vault_uri')}}"

    - name: Create a secret
      azure_rm_keyvaultsecret:
        secret_name: adminPassword
        secret_value: "<PASSWORD>"
        keyvault_uri: "{{ keyvaulturi }}"
        tags:
            app: ansible
            env: dev
            owner: ops