---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Look up secret when ansible host is general VM
    vars:
      url: 'https://kv-cs-ansible.vault.azure.net/'
      secretname: 'adminPassword'
    debug: msg="the value of this secret is {{lookup('azure_keyvault_secret',secretname,vault_url=url, client_id=client_id, secret=secret, tenant_id=tenant)}}"